# Generated by Django 3.0.7 on 2020-07-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('hostel', models.CharField(max_length=20)),
                ('room', models.IntegerField()),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
