# Generated by Django 3.0.7 on 2020-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
